on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Gatsby
        run: |
          npm i npm-check-updates gatsby -global
          npx gatsby new site https://github.com/hasura/gatsby-gitbook-starter
          cp -r docs/* site/content/
          cd site
          npx ncu -u -t patch
          npm install
          npm run build
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish --project-name=hardware-process ./site/public/
